# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='Confirm_Password',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
