# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170830_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Email',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
